name: seqneighbor_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython
  - anaconda::colorama
  - hnswlib==0.7.0
  - bioconda::jellyfish
  - memory_profiler==0.61.0
  - networkx
  - nbconvert
  - nltk
  - notebook
  - numba
  - numpy==1.26.4
  - pandas
  - pygraphviz
  - pynndescent==0.5.12
  - pysam==0.22.1
  - python==3.12
  - python-isal
  - requests
  - scanpy==1.10.1
  - scikit-learn==1.5.0
  - scipy
  - bioconda::sharedmem
  - python-xxhash==3.5.0
